sudo: required
services:
  - docker

before_install:
  - docker build -t alfa2beta/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true alfa2beta/docker-react-travis npm run test